### ISSUE TITLE
BUG: fillet on edges + cut

### ISSUE THREAD

**Issue by RemiTheWarrior** [ukaea/paramak#341]
When trying to cut a shape with a filleted shape, depending on how the edges are selected, an error is raised.
The following code raises an error:

```python
import paramak

width = 0.5
points = [
    (-width/2, -width/2),
    (width/2, -width/2),
    (width/2, width/2),
    (-width/2, width/2),
]
cutter = paramak.ExtrudeStraightShape(
    points=points,
    distance=2,
)
# cutter.solid = cutter.solid.edges('|Y').fillet(0.02)  # works
cutter.solid = cutter.solid.edges('#Z').fillet(0.02)  # Doesn't work

shape = paramak.CenterColumnShieldCylinder(1, 0.5, 1, cut=cutter)

shape.export_stp('test.stp')
```

Error:
```
Traceback (most recent call last):
  File "mwe.py", line 19, in <module>
    shape.export_stp('test.stp')
  File "/home/paramak/shape.py", line 446, in export_stp
    exporters.exportShape(self.solid, "STEP", f)
  File "/home/paramak/parametric_shapes/rotate_straight_shape.py", line 82, in solid
    self.create_solid()
  File "/home/paramak/parametric_shapes/rotate_straight_shape.py", line 131, in create_solid
    self.perform_boolean_operations(solid)
  File "/home/paramak/shape.py", line 715, in perform_boolean_operations
    solid = cut_solid(solid, self.cut)
  File "/home/paramak/utils.py", line 42, in cut_solid
    solid = solid.cut(cutter.solid)
  File "/root/anaconda3/lib/python3.7/site-packages/cadquery/cq.py", line 2780, in cut
    newS = solidRef.cut(*solidToCut)
  File "/root/anaconda3/lib/python3.7/site-packages/cadquery/occ_impl/shapes.py", line 1990, in cut
    return self._bool_op(self, toCut, cut_op)
  File "/root/anaconda3/lib/python3.7/site-packages/cadquery/occ_impl/shapes.py", line 609, in _bool_op
    return Shape.cast(op.Shape())
  File "/root/anaconda3/lib/python3.7/site-packages/cadquery/occ_impl/shapes.py", line 272, in cast
    t = obj.ShapeType()
AttributeError: 'NoneType' object has no attribute 'ShapeType'
```

**Comment by RemiTheWarrior** [comment]
In addition, the following cadquery code works fine which makes me think this is a paramak bug:
```python
import cadquery as cq

result = cq.Workplane("XY").circle(3.0).extrude(0.25)

cutter = cq.Workplane("XY").box(1, 1, 3)
cutter = cutter.edges('#Z').fillet(0.02)

result = result.cut(cutter)
```

**Comment by RemiTheWarrior** [comment]
Nevermind guys I got it working! Solution was: increase the extrusion distance of the cutting shape so that the fillet of the transerval edges is outside of the shape. Tricky.

Closing this
